version: '3.1'
services:
  mysql:
    image: 'mysql:5.5'
    environment:
      - MYSQL_USER=local_user
      - MYSQL_DATABASE=local_database
      - MYSQL_ROOT_PASSWORD=password
      # volumes:
      # Mounting the content of the database inside of a subfolder named mariadb_data
      # - './mariadb_data:/var/lib/mysql'
    ports:
      - '8306:3306'
  apache:
    image: php:5.6
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mounting the website inside of a subfolder named app
      - .:/var/www/htmlpassword
    ports:
      - 8000:80